name: Yarn Cypress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env: 
      selected_node_version: 18

    steps:
    - uses: actions/checkout@v3
    - name: Setup node_modules
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.selected_node_version }}

    - name: yarn install
      run: |
        yarn install

    - name: yarn run cypress
      run: |
        yarn run cypress verify
